//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SharedResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists. Please select different record.
        /// </summary>
        internal static string CustomerAlreadyExists {
            get {
                return ResourceManager.GetString("CustomerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists for 2 loan . Please select different record.
        /// </summary>
        internal static string CustomerAlreadyExistsForLoan {
            get {
                return ResourceManager.GetString("CustomerAlreadyExistsForLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Item To Delete.
        /// </summary>
        internal static string DeleteItemSelection {
            get {
                return ResourceManager.GetString("DeleteItemSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check you credentials or Try again Later.
        /// </summary>
        internal static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login session has been expired. Please login again.
        /// </summary>
        internal static string LoginSessionExpire {
            get {
                return ResourceManager.GetString("LoginSessionExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either New Customer or not having Kayamnidhi Balance.
        /// </summary>
        internal static string NewCustomerLoanNotAllowed {
            get {
                return ResourceManager.GetString("NewCustomerLoanNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully.
        /// </summary>
        internal static string RecordDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RecordDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Not Deleted Successfully. Please Try Later.
        /// </summary>
        internal static string RecordDeleteFailure {
            get {
                return ResourceManager.GetString("RecordDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully.
        /// </summary>
        internal static string RecordSavedSuccessfully {
            get {
                return ResourceManager.GetString("RecordSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Saved Successfully. Please Try Later.
        /// </summary>
        internal static string RecordSavingFailure {
            get {
                return ResourceManager.GetString("RecordSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully.
        /// </summary>
        internal static string RecordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("RecordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Updated Successfully. Please Try Later.
        /// </summary>
        internal static string RecordUpdateFailure {
            get {
                return ResourceManager.GetString("RecordUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select atleast one Customer.
        /// </summary>
        internal static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
    }
}
